name: Check formatting and linting (Frontend)

on:
  push:
    branches:
      - dev
      - master
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v4

      - name: Node modules caching (Frontend)
        id: cache-node-modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "frontend"

      - name: Install Frontend dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint
