name: Build (Frontend)

on:
  push:
    branches:
      - dev
      - master
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4

      - name: Node modules caching (Frontend)
        id: cache-node-modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "frontend"

      - name: Copy .env
        run: mv .env.example .env

      - name: Install Frontend dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build
